# Navigation Links

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /experience/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Projects
    url: /projects/
    weight: 40
  - name: Blog
    url: /blog/
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
